### ISSUE TITLE
Remove hard-coded fill colour from icons imported in css using background-image

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1123]
All icons that are imported into the css file using `url()` should not have its fill set inside the `url()`.  Instead, to allow different fill colours it should be set using `fill` css property.

## Expected behaviour

```
background-image: url('~icons/external.svg');
fill: #09707E;
```

## Current behaviour

An example:
```
background-image: url('~icons/external.svg?fill=#09707E');
```

**Comment by jaredh-um** [comment]
It is [not possible](https://css-tricks.com/solved-with-css-colorizing-svg-backgrounds/#the-problem-editing-svg-backgrounds) to apply fills in the DOM to an SVG used as a background-image, because it is treated as any other image. The colour must be set in the SVG, or in the URL as already occurs in this situation.
